name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
        - completed
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download the artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts
          path: ./artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: List downloaded files
        run: ls ./artifacts    
