name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ml-inference-api:latest
            docker stop ml-api || true
            docker rm ml-api || true
            docker run -d --name ml-api -p 8000:8000 --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/ml-inference-api:latest
