name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train_model.py

      - name: Run tests
        run: pytest test_app.py -v
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: /dist
  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Train model
        run: |
          pip install scikit-learn numpy
          python train_model.py

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-inference-api:latest
  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Train model
        run: |
          pip install scikit-learn numpy
          python train_model.py

      - name: Build Docker image
        run: docker build -t ml-inference-api:latest .   